### ISSUE TITLE
False positive error on first migration: Found a non-consecutive migration ID on file

### ISSUE THREAD

**Issue by steve-taylor** [ThomWright/postgres-migrations#107]
I'm trying to run my first ever migration, starting with a single SQL file (generated by `drizzle-kit generate:pg`) called `0000_gigantic_pyro.sql`. When I run it, I get this error:

```json
{
  "errorType": "Error",
  "errorMessage": "Found a non-consecutive migration ID on file: '0000_gigantic_pyro.sql'",
  "trace": [
    "Error: Found a non-consecutive migration ID on file: '0000_gigantic_pyro.sql'",
    "    at Object.validateMigrationOrdering (/var/task/node_modules/postgres-migrations/dist/validation.js:9:15)",
    "    at Object.loadMigrationFiles (/var/task/node_modules/postgres-migrations/dist/files-loader.js:35:18)",
    "    at async migrate (/var/task/node_modules/postgres-migrations/dist/migrate.js:35:32)",
    "    at async Runtime.migrate [as handler] (file:///var/task/sst/migrations/src/index.mjs:23:3)"
  ]
}
```

Here's the transpiled migration code:

```js
import { createRequire as topLevelCreateRequire } from 'module';
const require = topLevelCreateRequire(import.meta.url);
import { fileURLToPath as topLevelFileUrlToPath, URL as topLevelURL } from "url"
const __dirname = topLevelFileUrlToPath(new topLevelURL(".", import.meta.url))

var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });

// sst/migrations/src/index.ts
import path from "path";
import { migrate as pgmigrate } from "postgres-migrations";
import url from "url";
async function migrate() {
  const dbConfig = {
    host: process.env.DB_HOST,
    port: parseInt(process.env.DB_PORT),
    database: process.env.DB_NAME,
    user: process.env.DB_USER,
    password: process.env.DB_PASS,
    ensureDatabaseExists: true,
    defaultDatabase: "postgres"
  };
  await pgmigrate(
    dbConfig,
    path.resolve(
      path.dirname(url.fileURLToPath(import.meta.url)),
      "../../../packages/schema/migrations"
    )
  );
}
__name(migrate, "migrate");
export {
  migrate
};
//# sourceMappingURL=index.mjs.map
```

and here's how the file system is laid out (as you may guess, this is on Lambda):

<img width="235" alt="image" src="https://github.com/ThomWright/postgres-migrations/assets/1135589/e05c51ad-adb1-4412-a551-f8909c749246">

What exactly is wrong with the name `0000_gigantic_pyro.sql` that would trigger this error? The error seems wrong, since this filename follows "simple naming" and matches `^(-?\d+)[-_]?(.*).(sql|js)$`.

**Comment by steve-taylor** [comment]
[This](https://github.com/ThomWright/postgres-migrations/blob/master/src/files-loader.ts#L35) looks like a bug:

```js
  const migrationFiles = [
    path.join(__dirname, "migrations/0_create-migrations-table.sql"),
    ...fileNames.map((fileName) => path.resolve(directory, fileName)),
  ].filter(isValidFile)
```

It should instead be

```js
  const migrationFiles = fileNames
    .map((fileName) => path.resolve(directory, fileName))
    .filter(isValidFile)
```

I don't see why this should be opinionated about the name of the first migration file. If you use `migrations/0_create-migrations-table.sql`, then both of the above will do the same thing.

I'll create a pull request to fix this.

**Comment by steve-taylor** [comment]
Actually not really a bug, now that I understand `0_create-migrations-table.sql` is an internal file. It's unfortunate that it was implemented this way. I don't see an easy way around it.
