### ISSUE TITLE
[ERR_INVALID_ARG_TYPE] A request to make an error message more verbose

### ISSUE THREAD

**Issue by arthur-kv** [ThomWright/postgres-migrations#26]
Hi, guys! 

We receive the following error If the next migration file name in the list starts with a number incremented by more than one, e.g.

```
00001.sql
(a file 00002.sql is absent)
00003.sql
```

Is it possible to make this error more verbose?

This is the error message itself:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:258:10)
    at WriteStream.Writable.write (_stream_writable.js:292:21)
    at process.on (/run_migrations.js:33:18)
    at process.emit (events.js:189:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
Emitted 'error' event at:
    at validChunk (_stream_writable.js:261:12)
    at WriteStream.Writable.write (_stream_writable.js:292:21)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

Regards

**Comment by ThomWright** [comment]
Hi,

Which version are you running?

The current version has tests for this, and the error thrown will have the message: `Error: Migration failed. Reason: Found a non-consecutive migration ID on file: '00003.sql'`.

**Comment by arthur-kv** [comment]
Oh, found an issue on my end. Now I see the error message you've mentioned.

Thank you!
